# Generated by Django 3.2.7 on 2021-09-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_article_article_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_introduction',
            field=models.TextField(default='...', max_length=500, verbose_name='Вступление статьи'),
        ),
    ]
