# Generated by Django 3.2.7 on 2021-09-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210917_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_author',
        ),
    ]
