# Generated by Django 3.2.7 on 2021-09-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_article_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
