# Generated by Django 3.2.7 on 2021-09-24 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 0, 0), null=True, verbose_name='дата публикации'),
        ),
    ]
