# Generated by Django 3.2.7 on 2021-10-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_comment_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.IntegerField(choices=[(1, 'Admin'), (10, 'Visitor')], default=10),
        ),
    ]
