# Generated by Django 3.2.7 on 2021-10-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.IntegerField(choices=[(1, 'Admin'), (10, 'Visitor'), (20, 'Unknown')], default=10),
        ),
    ]
